[package]
description = "mimicks python's pexpect"
name = "rexpect"
version = "0.1.0"
authors = ["Philipp Keller <philipp.keller@gmail.com>"]

[dependencies]
nix = "0.9"
regex = "0.2"
error-chain = "0.10"
tempfile = "2"
lazy_static = "0.2"