[package]
description = "mimicks python's pexpect"
name = "rexpect"
version = "0.1.0"
authors = ["Philipp Keller <philipp.keller@gmail.com>"]

[dependencies]
nix = {git = "https://github.com/nix-rust/nix.git"}
regex = "0.2"
error-chain = "0.10"
lazy_static = "0.2"
libc="0.2"